name: shop_app
description: Created by - The Flutter Way

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  start plugin core app
  dio: ^5.3.3
  flutter_phoenix: ^1.0.0
  flutter_share: ^2.0.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  device_info: ^2.0.0
  path_provider: ^2.1.1
  fluttertoast: ^8.1.1
  flutter_local_notifications: ^16.1.0
  connectivity: ^3.0.3
  flutter_widget_from_html: ^0.14.6
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.3
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  decimal: ^2.3.3
  json_annotation: 4.8.1
  intl: ^0.19.0


dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mobx_codegen: ^2.4.0
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
